// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.2
// source: api/liveclass/liveclass.proto

package liveclass

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LiveClassCallBackEvent int32

const (
	LiveClassCallBackEvent_Unknown LiveClassCallBackEvent = 0
	//说课结束(针对说课教研会议)
	LiveClassCallBackEvent_SpeakClassEnd LiveClassCallBackEvent = 1
	//直播开始
	LiveClassCallBackEvent_LiveBegin LiveClassCallBackEvent = 2
	//直播结束
	LiveClassCallBackEvent_LiveEnd LiveClassCallBackEvent = 3
)

// Enum value maps for LiveClassCallBackEvent.
var (
	LiveClassCallBackEvent_name = map[int32]string{
		0: "Unknown",
		1: "SpeakClassEnd",
		2: "LiveBegin",
		3: "LiveEnd",
	}
	LiveClassCallBackEvent_value = map[string]int32{
		"Unknown":       0,
		"SpeakClassEnd": 1,
		"LiveBegin":     2,
		"LiveEnd":       3,
	}
)

func (x LiveClassCallBackEvent) Enum() *LiveClassCallBackEvent {
	p := new(LiveClassCallBackEvent)
	*p = x
	return p
}

func (x LiveClassCallBackEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LiveClassCallBackEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_api_liveclass_liveclass_proto_enumTypes[0].Descriptor()
}

func (LiveClassCallBackEvent) Type() protoreflect.EnumType {
	return &file_api_liveclass_liveclass_proto_enumTypes[0]
}

func (x LiveClassCallBackEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LiveClassCallBackEvent.Descriptor instead.
func (LiveClassCallBackEvent) EnumDescriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{0}
}

type LiveClassCallBackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *LiveClassCallBackRequest) Reset() {
	*x = LiveClassCallBackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_liveclass_liveclass_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveClassCallBackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveClassCallBackRequest) ProtoMessage() {}

func (x *LiveClassCallBackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_liveclass_liveclass_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveClassCallBackRequest.ProtoReflect.Descriptor instead.
func (*LiveClassCallBackRequest) Descriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{0}
}

func (x *LiveClassCallBackRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type LiveClassCallBackReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success string `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *LiveClassCallBackReply) Reset() {
	*x = LiveClassCallBackReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_liveclass_liveclass_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveClassCallBackReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveClassCallBackReply) ProtoMessage() {}

func (x *LiveClassCallBackReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_liveclass_liveclass_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveClassCallBackReply.ProtoReflect.Descriptor instead.
func (*LiveClassCallBackReply) Descriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{1}
}

func (x *LiveClassCallBackReply) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

type LiveClassDelayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeetingId     string `protobuf:"bytes,1,opt,name=meetingId,proto3" json:"meetingId,omitempty"`
	DelayDuration int64  `protobuf:"varint,2,opt,name=delayDuration,proto3" json:"delayDuration,omitempty"`
}

func (x *LiveClassDelayRequest) Reset() {
	*x = LiveClassDelayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_liveclass_liveclass_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveClassDelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveClassDelayRequest) ProtoMessage() {}

func (x *LiveClassDelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_liveclass_liveclass_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveClassDelayRequest.ProtoReflect.Descriptor instead.
func (*LiveClassDelayRequest) Descriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{2}
}

func (x *LiveClassDelayRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *LiveClassDelayRequest) GetDelayDuration() int64 {
	if x != nil {
		return x.DelayDuration
	}
	return 0
}

type LiveClassDelayReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success string `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *LiveClassDelayReply) Reset() {
	*x = LiveClassDelayReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_liveclass_liveclass_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveClassDelayReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveClassDelayReply) ProtoMessage() {}

func (x *LiveClassDelayReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_liveclass_liveclass_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveClassDelayReply.ProtoReflect.Descriptor instead.
func (*LiveClassDelayReply) Descriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{3}
}

func (x *LiveClassDelayReply) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

type LiveClassBeginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeetingId string `protobuf:"bytes,1,opt,name=meetingId,proto3" json:"meetingId,omitempty"`
}

func (x *LiveClassBeginRequest) Reset() {
	*x = LiveClassBeginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_liveclass_liveclass_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveClassBeginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveClassBeginRequest) ProtoMessage() {}

func (x *LiveClassBeginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_liveclass_liveclass_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveClassBeginRequest.ProtoReflect.Descriptor instead.
func (*LiveClassBeginRequest) Descriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{4}
}

func (x *LiveClassBeginRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

type LiveClassBeginReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success string `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *LiveClassBeginReply) Reset() {
	*x = LiveClassBeginReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_liveclass_liveclass_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveClassBeginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveClassBeginReply) ProtoMessage() {}

func (x *LiveClassBeginReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_liveclass_liveclass_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveClassBeginReply.ProtoReflect.Descriptor instead.
func (*LiveClassBeginReply) Descriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{5}
}

func (x *LiveClassBeginReply) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

type LiveClassEndRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeetingId string `protobuf:"bytes,1,opt,name=meetingId,proto3" json:"meetingId,omitempty"`
}

func (x *LiveClassEndRequest) Reset() {
	*x = LiveClassEndRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_liveclass_liveclass_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveClassEndRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveClassEndRequest) ProtoMessage() {}

func (x *LiveClassEndRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_liveclass_liveclass_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveClassEndRequest.ProtoReflect.Descriptor instead.
func (*LiveClassEndRequest) Descriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{6}
}

func (x *LiveClassEndRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

type LiveClassEndReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success string `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *LiveClassEndReply) Reset() {
	*x = LiveClassEndReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_liveclass_liveclass_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveClassEndReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveClassEndReply) ProtoMessage() {}

func (x *LiveClassEndReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_liveclass_liveclass_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveClassEndReply.ProtoReflect.Descriptor instead.
func (*LiveClassEndReply) Descriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{7}
}

func (x *LiveClassEndReply) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

type LiveClassCommonCallBackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeetingId string                 `protobuf:"bytes,1,opt,name=meetingId,proto3" json:"meetingId,omitempty"`
	Event     LiveClassCallBackEvent `protobuf:"varint,2,opt,name=Event,proto3,enum=api.liveclass.LiveClassCallBackEvent" json:"Event,omitempty"`
	Data      []byte                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *LiveClassCommonCallBackRequest) Reset() {
	*x = LiveClassCommonCallBackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_liveclass_liveclass_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveClassCommonCallBackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveClassCommonCallBackRequest) ProtoMessage() {}

func (x *LiveClassCommonCallBackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_liveclass_liveclass_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveClassCommonCallBackRequest.ProtoReflect.Descriptor instead.
func (*LiveClassCommonCallBackRequest) Descriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{8}
}

func (x *LiveClassCommonCallBackRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *LiveClassCommonCallBackRequest) GetEvent() LiveClassCallBackEvent {
	if x != nil {
		return x.Event
	}
	return LiveClassCallBackEvent_Unknown
}

func (x *LiveClassCommonCallBackRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type LiveClassCommonCallBackReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success string `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *LiveClassCommonCallBackReply) Reset() {
	*x = LiveClassCommonCallBackReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_liveclass_liveclass_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveClassCommonCallBackReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveClassCommonCallBackReply) ProtoMessage() {}

func (x *LiveClassCommonCallBackReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_liveclass_liveclass_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveClassCommonCallBackReply.ProtoReflect.Descriptor instead.
func (*LiveClassCommonCallBackReply) Descriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{9}
}

func (x *LiveClassCommonCallBackReply) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

type InviteGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupIds  []int64 `protobuf:"varint,1,rep,packed,name=groupIds,proto3" json:"groupIds,omitempty"`
	MeetingId string  `protobuf:"bytes,2,opt,name=meetingId,proto3" json:"meetingId,omitempty"`
}

func (x *InviteGroupRequest) Reset() {
	*x = InviteGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_liveclass_liveclass_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InviteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteGroupRequest) ProtoMessage() {}

func (x *InviteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_liveclass_liveclass_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteGroupRequest.ProtoReflect.Descriptor instead.
func (*InviteGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{10}
}

func (x *InviteGroupRequest) GetGroupIds() []int64 {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

func (x *InviteGroupRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

type InviteGroupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success string `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *InviteGroupReply) Reset() {
	*x = InviteGroupReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_liveclass_liveclass_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InviteGroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteGroupReply) ProtoMessage() {}

func (x *InviteGroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_liveclass_liveclass_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteGroupReply.ProtoReflect.Descriptor instead.
func (*InviteGroupReply) Descriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{11}
}

func (x *InviteGroupReply) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

type GetTeachingUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeetingId string `protobuf:"bytes,1,opt,name=meetingId,proto3" json:"meetingId,omitempty"`
}

func (x *GetTeachingUserRequest) Reset() {
	*x = GetTeachingUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_liveclass_liveclass_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTeachingUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeachingUserRequest) ProtoMessage() {}

func (x *GetTeachingUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_liveclass_liveclass_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeachingUserRequest.ProtoReflect.Descriptor instead.
func (*GetTeachingUserRequest) Descriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{12}
}

func (x *GetTeachingUserRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

type GetTeachingUserReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetTeachingUserReply) Reset() {
	*x = GetTeachingUserReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_liveclass_liveclass_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTeachingUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeachingUserReply) ProtoMessage() {}

func (x *GetTeachingUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_liveclass_liveclass_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeachingUserReply.ProtoReflect.Descriptor instead.
func (*GetTeachingUserReply) Descriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{13}
}

func (x *GetTeachingUserReply) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateInfiMeetingMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 备课组ID
}

func (x *UpdateInfiMeetingMemberRequest) Reset() {
	*x = UpdateInfiMeetingMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_liveclass_liveclass_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateInfiMeetingMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInfiMeetingMemberRequest) ProtoMessage() {}

func (x *UpdateInfiMeetingMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_liveclass_liveclass_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInfiMeetingMemberRequest.ProtoReflect.Descriptor instead.
func (*UpdateInfiMeetingMemberRequest) Descriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateInfiMeetingMemberRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateInfiMeetingMemberReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success string `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UpdateInfiMeetingMemberReply) Reset() {
	*x = UpdateInfiMeetingMemberReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_liveclass_liveclass_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateInfiMeetingMemberReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInfiMeetingMemberReply) ProtoMessage() {}

func (x *UpdateInfiMeetingMemberReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_liveclass_liveclass_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInfiMeetingMemberReply.ProtoReflect.Descriptor instead.
func (*UpdateInfiMeetingMemberReply) Descriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateInfiMeetingMemberReply) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

type GetUserTypeInTeachingActivityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeachingActivityId string `protobuf:"bytes,1,opt,name=teachingActivityId,proto3" json:"teachingActivityId,omitempty"`
	UserId             int64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetUserTypeInTeachingActivityRequest) Reset() {
	*x = GetUserTypeInTeachingActivityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_liveclass_liveclass_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserTypeInTeachingActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTypeInTeachingActivityRequest) ProtoMessage() {}

func (x *GetUserTypeInTeachingActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_liveclass_liveclass_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTypeInTeachingActivityRequest.ProtoReflect.Descriptor instead.
func (*GetUserTypeInTeachingActivityRequest) Descriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserTypeInTeachingActivityRequest) GetTeachingActivityId() string {
	if x != nil {
		return x.TeachingActivityId
	}
	return ""
}

func (x *GetUserTypeInTeachingActivityRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserTypeInTeachingActivityReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserType string `protobuf:"bytes,1,opt,name=userType,proto3" json:"userType,omitempty"`
}

func (x *GetUserTypeInTeachingActivityReply) Reset() {
	*x = GetUserTypeInTeachingActivityReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_liveclass_liveclass_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserTypeInTeachingActivityReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTypeInTeachingActivityReply) ProtoMessage() {}

func (x *GetUserTypeInTeachingActivityReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_liveclass_liveclass_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTypeInTeachingActivityReply.ProtoReflect.Descriptor instead.
func (*GetUserTypeInTeachingActivityReply) Descriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserTypeInTeachingActivityReply) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

type VideoTranscodeStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId string `protobuf:"bytes,1,opt,name=fileId,proto3" json:"fileId,omitempty"`
	Status int64  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *VideoTranscodeStatusRequest) Reset() {
	*x = VideoTranscodeStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_liveclass_liveclass_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoTranscodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoTranscodeStatusRequest) ProtoMessage() {}

func (x *VideoTranscodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_liveclass_liveclass_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoTranscodeStatusRequest.ProtoReflect.Descriptor instead.
func (*VideoTranscodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{18}
}

func (x *VideoTranscodeStatusRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *VideoTranscodeStatusRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type VideoTranscodeStatusRequestReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success string `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *VideoTranscodeStatusRequestReply) Reset() {
	*x = VideoTranscodeStatusRequestReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_liveclass_liveclass_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoTranscodeStatusRequestReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoTranscodeStatusRequestReply) ProtoMessage() {}

func (x *VideoTranscodeStatusRequestReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_liveclass_liveclass_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoTranscodeStatusRequestReply.ProtoReflect.Descriptor instead.
func (*VideoTranscodeStatusRequestReply) Descriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{19}
}

func (x *VideoTranscodeStatusRequestReply) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

type GenTrReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeachingActivityId string `protobuf:"bytes,1,opt,name=TeachingActivityId,proto3" json:"TeachingActivityId,omitempty"`
}

func (x *GenTrReportRequest) Reset() {
	*x = GenTrReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_liveclass_liveclass_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenTrReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenTrReportRequest) ProtoMessage() {}

func (x *GenTrReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_liveclass_liveclass_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenTrReportRequest.ProtoReflect.Descriptor instead.
func (*GenTrReportRequest) Descriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{20}
}

func (x *GenTrReportRequest) GetTeachingActivityId() string {
	if x != nil {
		return x.TeachingActivityId
	}
	return ""
}

type GenTrReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *GenTrReportResponse) Reset() {
	*x = GenTrReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_liveclass_liveclass_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenTrReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenTrReportResponse) ProtoMessage() {}

func (x *GenTrReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_liveclass_liveclass_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenTrReportResponse.ProtoReflect.Descriptor instead.
func (*GenTrReportResponse) Descriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{21}
}

func (x *GenTrReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LiveClassRelatedGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RelatedGroupId int64 `protobuf:"varint,1,opt,name=relatedGroupId,proto3" json:"relatedGroupId,omitempty"`
}

func (x *LiveClassRelatedGroupRequest) Reset() {
	*x = LiveClassRelatedGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_liveclass_liveclass_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveClassRelatedGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveClassRelatedGroupRequest) ProtoMessage() {}

func (x *LiveClassRelatedGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_liveclass_liveclass_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveClassRelatedGroupRequest.ProtoReflect.Descriptor instead.
func (*LiveClassRelatedGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{22}
}

func (x *LiveClassRelatedGroupRequest) GetRelatedGroupId() int64 {
	if x != nil {
		return x.RelatedGroupId
	}
	return 0
}

// 定义RelatedGroup消息
type RelatedLiveClass struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeetingId   string `protobuf:"bytes,1,opt,name=meetingId,proto3" json:"meetingId,omitempty"`
	InviterName string `protobuf:"bytes,2,opt,name=inviterName,proto3" json:"inviterName,omitempty"`
	Title       string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *RelatedLiveClass) Reset() {
	*x = RelatedLiveClass{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_liveclass_liveclass_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelatedLiveClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelatedLiveClass) ProtoMessage() {}

func (x *RelatedLiveClass) ProtoReflect() protoreflect.Message {
	mi := &file_api_liveclass_liveclass_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelatedLiveClass.ProtoReflect.Descriptor instead.
func (*RelatedLiveClass) Descriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{23}
}

func (x *RelatedLiveClass) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *RelatedLiveClass) GetInviterName() string {
	if x != nil {
		return x.InviterName
	}
	return ""
}

func (x *RelatedLiveClass) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type LiveClassRelatedGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RelatedLiveClass []*RelatedLiveClass `protobuf:"bytes,1,rep,name=relatedLiveClass,proto3" json:"relatedLiveClass,omitempty"`
}

func (x *LiveClassRelatedGroupResponse) Reset() {
	*x = LiveClassRelatedGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_liveclass_liveclass_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveClassRelatedGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveClassRelatedGroupResponse) ProtoMessage() {}

func (x *LiveClassRelatedGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_liveclass_liveclass_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveClassRelatedGroupResponse.ProtoReflect.Descriptor instead.
func (*LiveClassRelatedGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_liveclass_liveclass_proto_rawDescGZIP(), []int{24}
}

func (x *LiveClassRelatedGroupResponse) GetRelatedLiveClass() []*RelatedLiveClass {
	if x != nil {
		return x.RelatedLiveClass
	}
	return nil
}

var File_api_liveclass_liveclass_proto protoreflect.FileDescriptor

var file_api_liveclass_liveclass_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x69, 0x76, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2f,
	0x6c, 0x69, 0x76, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0d, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x22, 0x2e,
	0x0a, 0x18, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x43, 0x61, 0x6c, 0x6c, 0x42,
	0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x32,
	0x0a, 0x16, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x43, 0x61, 0x6c, 0x6c, 0x42,
	0x61, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x22, 0x5b, 0x0a, 0x15, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x44,
	0x65, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6d,
	0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x64, 0x65, 0x6c,
	0x61, 0x79, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0d, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x2f, 0x0a, 0x13, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x44, 0x65, 0x6c, 0x61,
	0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x22, 0x35, 0x0a, 0x15, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x42, 0x65, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x65,
	0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65,
	0x65, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x13, 0x4c, 0x69, 0x76, 0x65, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x33, 0x0a, 0x13, 0x4c, 0x69, 0x76, 0x65,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x45, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x22, 0x2d, 0x0a,
	0x11, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x45, 0x6e, 0x64, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x8f, 0x01, 0x0a,
	0x1e, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x43, 0x61, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x3b, 0x0a,
	0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x4c, 0x69, 0x76,
	0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x43, 0x61, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x38,
	0x0a, 0x1c, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x4e, 0x0a, 0x12, 0x49, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65,
	0x65, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d,
	0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x10, 0x49, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x36, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x22, 0x2a,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x30, 0x0a, 0x1e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x69, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x38, 0x0a, 0x1c,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x69, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e,
	0x67, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x6e, 0x0a, 0x24, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x54, 0x65, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e,
	0x0a, 0x12, 0x74, 0x65, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x74, 0x65, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x67, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x40, 0x0a, 0x22, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x54, 0x65, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x22, 0x4d, 0x0a, 0x1b, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3c, 0x0a, 0x20, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x44, 0x0a, 0x12, 0x47, 0x65, 0x6e, 0x54, 0x72, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x12, 0x54,
	0x65, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x54, 0x65, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x67, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x13, 0x47,
	0x65, 0x6e, 0x54, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x46, 0x0a, 0x1c,
	0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x64, 0x22, 0x68, 0x0a, 0x10, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x4c,
	0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x65, 0x74,
	0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x65,
	0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x6c,
	0x0a, 0x1d, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x6c, 0x61, 0x74,
	0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4b, 0x0a, 0x10, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c,
	0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x6c, 0x69, 0x76, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x65,
	0x64, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x10, 0x72, 0x65, 0x6c, 0x61,
	0x74, 0x65, 0x64, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x2a, 0x54, 0x0a, 0x16,
	0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x43, 0x61, 0x6c, 0x6c, 0x42, 0x61, 0x63,
	0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x70, 0x65, 0x61, 0x6b, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x45, 0x6e, 0x64, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4c, 0x69, 0x76, 0x65, 0x42, 0x65,
	0x67, 0x69, 0x6e, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x4c, 0x69, 0x76, 0x65, 0x45, 0x6e, 0x64,
	0x10, 0x03, 0x32, 0xe6, 0x07, 0x0a, 0x09, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x12, 0x75, 0x0a, 0x17, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x12, 0x2d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x4c, 0x69, 0x76, 0x65,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x42,
	0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x6c, 0x69, 0x76, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x42, 0x61,
	0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x63, 0x0a, 0x11, 0x4c, 0x69, 0x76, 0x65, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x43, 0x61, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x12, 0x27, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x4c, 0x69, 0x76,
	0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x43, 0x61, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x69, 0x76, 0x65,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x43,
	0x61, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5a, 0x0a, 0x0e,
	0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x12, 0x24,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x4c,
	0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x63,
	0x6c, 0x61, 0x73, 0x73, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x44, 0x65,
	0x6c, 0x61, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5a, 0x0a, 0x0e, 0x4c, 0x69, 0x76, 0x65,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x6c, 0x69, 0x76, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x2e, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x54, 0x0a, 0x0c, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x45, 0x6e, 0x64, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x63,
	0x6c, 0x61, 0x73, 0x73, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x45, 0x6e,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c,
	0x69, 0x76, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x45, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x51, 0x0a, 0x0b, 0x49, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x6c, 0x69, 0x76, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x49, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5d, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x69,
	0x76, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x73, 0x0a, 0x14,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x63,
	0x6c, 0x61, 0x73, 0x73, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63,
	0x6f, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x54, 0x0a, 0x0b, 0x47, 0x65, 0x6e, 0x54, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x2e, 0x47, 0x65, 0x6e, 0x54, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x63, 0x6c,
	0x61, 0x73, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x54, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x72, 0x0a, 0x15, 0x4c, 0x69, 0x76, 0x65, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x12, 0x2b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x2e, 0x4c, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x65,
	0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x4c, 0x69,
	0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2a, 0x0a, 0x0d, 0x61,
	0x70, 0x69, 0x2e, 0x6c, 0x69, 0x76, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x50, 0x01, 0x5a, 0x17,
	0x61, 0x70, 0x69, 0x2f, 0x6c, 0x69, 0x76, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x3b, 0x6c, 0x69,
	0x76, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_liveclass_liveclass_proto_rawDescOnce sync.Once
	file_api_liveclass_liveclass_proto_rawDescData = file_api_liveclass_liveclass_proto_rawDesc
)

func file_api_liveclass_liveclass_proto_rawDescGZIP() []byte {
	file_api_liveclass_liveclass_proto_rawDescOnce.Do(func() {
		file_api_liveclass_liveclass_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_liveclass_liveclass_proto_rawDescData)
	})
	return file_api_liveclass_liveclass_proto_rawDescData
}

var file_api_liveclass_liveclass_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_liveclass_liveclass_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_api_liveclass_liveclass_proto_goTypes = []interface{}{
	(LiveClassCallBackEvent)(0),                  // 0: api.liveclass.LiveClassCallBackEvent
	(*LiveClassCallBackRequest)(nil),             // 1: api.liveclass.LiveClassCallBackRequest
	(*LiveClassCallBackReply)(nil),               // 2: api.liveclass.LiveClassCallBackReply
	(*LiveClassDelayRequest)(nil),                // 3: api.liveclass.LiveClassDelayRequest
	(*LiveClassDelayReply)(nil),                  // 4: api.liveclass.LiveClassDelayReply
	(*LiveClassBeginRequest)(nil),                // 5: api.liveclass.LiveClassBeginRequest
	(*LiveClassBeginReply)(nil),                  // 6: api.liveclass.LiveClassBeginReply
	(*LiveClassEndRequest)(nil),                  // 7: api.liveclass.LiveClassEndRequest
	(*LiveClassEndReply)(nil),                    // 8: api.liveclass.LiveClassEndReply
	(*LiveClassCommonCallBackRequest)(nil),       // 9: api.liveclass.LiveClassCommonCallBackRequest
	(*LiveClassCommonCallBackReply)(nil),         // 10: api.liveclass.LiveClassCommonCallBackReply
	(*InviteGroupRequest)(nil),                   // 11: api.liveclass.InviteGroupRequest
	(*InviteGroupReply)(nil),                     // 12: api.liveclass.InviteGroupReply
	(*GetTeachingUserRequest)(nil),               // 13: api.liveclass.GetTeachingUserRequest
	(*GetTeachingUserReply)(nil),                 // 14: api.liveclass.GetTeachingUserReply
	(*UpdateInfiMeetingMemberRequest)(nil),       // 15: api.liveclass.UpdateInfiMeetingMemberRequest
	(*UpdateInfiMeetingMemberReply)(nil),         // 16: api.liveclass.UpdateInfiMeetingMemberReply
	(*GetUserTypeInTeachingActivityRequest)(nil), // 17: api.liveclass.GetUserTypeInTeachingActivityRequest
	(*GetUserTypeInTeachingActivityReply)(nil),   // 18: api.liveclass.GetUserTypeInTeachingActivityReply
	(*VideoTranscodeStatusRequest)(nil),          // 19: api.liveclass.VideoTranscodeStatusRequest
	(*VideoTranscodeStatusRequestReply)(nil),     // 20: api.liveclass.VideoTranscodeStatusRequestReply
	(*GenTrReportRequest)(nil),                   // 21: api.liveclass.GenTrReportRequest
	(*GenTrReportResponse)(nil),                  // 22: api.liveclass.GenTrReportResponse
	(*LiveClassRelatedGroupRequest)(nil),         // 23: api.liveclass.LiveClassRelatedGroupRequest
	(*RelatedLiveClass)(nil),                     // 24: api.liveclass.RelatedLiveClass
	(*LiveClassRelatedGroupResponse)(nil),        // 25: api.liveclass.LiveClassRelatedGroupResponse
}
var file_api_liveclass_liveclass_proto_depIdxs = []int32{
	0,  // 0: api.liveclass.LiveClassCommonCallBackRequest.Event:type_name -> api.liveclass.LiveClassCallBackEvent
	24, // 1: api.liveclass.LiveClassRelatedGroupResponse.relatedLiveClass:type_name -> api.liveclass.RelatedLiveClass
	9,  // 2: api.liveclass.LiveClass.LiveClassCommonCallBack:input_type -> api.liveclass.LiveClassCommonCallBackRequest
	1,  // 3: api.liveclass.LiveClass.LiveClassCallBack:input_type -> api.liveclass.LiveClassCallBackRequest
	3,  // 4: api.liveclass.LiveClass.LiveClassDelay:input_type -> api.liveclass.LiveClassDelayRequest
	5,  // 5: api.liveclass.LiveClass.LiveClassBegin:input_type -> api.liveclass.LiveClassBeginRequest
	7,  // 6: api.liveclass.LiveClass.LiveClassEnd:input_type -> api.liveclass.LiveClassEndRequest
	11, // 7: api.liveclass.LiveClass.InviteGroup:input_type -> api.liveclass.InviteGroupRequest
	13, // 8: api.liveclass.LiveClass.GetTeachingUser:input_type -> api.liveclass.GetTeachingUserRequest
	19, // 9: api.liveclass.LiveClass.VideoTranscodeStatus:input_type -> api.liveclass.VideoTranscodeStatusRequest
	21, // 10: api.liveclass.LiveClass.GenTrReport:input_type -> api.liveclass.GenTrReportRequest
	23, // 11: api.liveclass.LiveClass.LiveClassRelatedGroup:input_type -> api.liveclass.LiveClassRelatedGroupRequest
	10, // 12: api.liveclass.LiveClass.LiveClassCommonCallBack:output_type -> api.liveclass.LiveClassCommonCallBackReply
	2,  // 13: api.liveclass.LiveClass.LiveClassCallBack:output_type -> api.liveclass.LiveClassCallBackReply
	4,  // 14: api.liveclass.LiveClass.LiveClassDelay:output_type -> api.liveclass.LiveClassDelayReply
	6,  // 15: api.liveclass.LiveClass.LiveClassBegin:output_type -> api.liveclass.LiveClassBeginReply
	8,  // 16: api.liveclass.LiveClass.LiveClassEnd:output_type -> api.liveclass.LiveClassEndReply
	12, // 17: api.liveclass.LiveClass.InviteGroup:output_type -> api.liveclass.InviteGroupReply
	14, // 18: api.liveclass.LiveClass.GetTeachingUser:output_type -> api.liveclass.GetTeachingUserReply
	20, // 19: api.liveclass.LiveClass.VideoTranscodeStatus:output_type -> api.liveclass.VideoTranscodeStatusRequestReply
	22, // 20: api.liveclass.LiveClass.GenTrReport:output_type -> api.liveclass.GenTrReportResponse
	25, // 21: api.liveclass.LiveClass.LiveClassRelatedGroup:output_type -> api.liveclass.LiveClassRelatedGroupResponse
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_liveclass_liveclass_proto_init() }
func file_api_liveclass_liveclass_proto_init() {
	if File_api_liveclass_liveclass_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_liveclass_liveclass_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveClassCallBackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_liveclass_liveclass_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveClassCallBackReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_liveclass_liveclass_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveClassDelayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_liveclass_liveclass_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveClassDelayReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_liveclass_liveclass_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveClassBeginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_liveclass_liveclass_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveClassBeginReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_liveclass_liveclass_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveClassEndRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_liveclass_liveclass_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveClassEndReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_liveclass_liveclass_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveClassCommonCallBackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_liveclass_liveclass_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveClassCommonCallBackReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_liveclass_liveclass_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InviteGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_liveclass_liveclass_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InviteGroupReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_liveclass_liveclass_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTeachingUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_liveclass_liveclass_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTeachingUserReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_liveclass_liveclass_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateInfiMeetingMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_liveclass_liveclass_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateInfiMeetingMemberReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_liveclass_liveclass_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserTypeInTeachingActivityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_liveclass_liveclass_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserTypeInTeachingActivityReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_liveclass_liveclass_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoTranscodeStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_liveclass_liveclass_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoTranscodeStatusRequestReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_liveclass_liveclass_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenTrReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_liveclass_liveclass_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenTrReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_liveclass_liveclass_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveClassRelatedGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_liveclass_liveclass_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelatedLiveClass); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_liveclass_liveclass_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveClassRelatedGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_liveclass_liveclass_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_liveclass_liveclass_proto_goTypes,
		DependencyIndexes: file_api_liveclass_liveclass_proto_depIdxs,
		EnumInfos:         file_api_liveclass_liveclass_proto_enumTypes,
		MessageInfos:      file_api_liveclass_liveclass_proto_msgTypes,
	}.Build()
	File_api_liveclass_liveclass_proto = out.File
	file_api_liveclass_liveclass_proto_rawDesc = nil
	file_api_liveclass_liveclass_proto_goTypes = nil
	file_api_liveclass_liveclass_proto_depIdxs = nil
}
